# exported from PySB model 'model'

import numpy as np
from pysb.integrate import Solver
import pylab as pl
import matplotlib.pyplot as plt
from pysb import Model, Monomer, Parameter, Expression, Compartment, Rule, Observable, Initial, MatchOnce, Annotation, ANY, WILD

Model()

Monomer('Noxa', ['Mcl1'])
Monomer('Apop', ['Xiap', 'C3pro'])
Monomer('ParpU', ['C3A'])
Monomer('C8A', ['Bar', 'BidU', 'C3pro'])
Monomer('DISC', ['C8pro', 'Flip'])
Monomer('SmacM', ['BakA', 'BaxA'])
Monomer('BaxM', ['BaxA', 'BidM'])
Monomer('Hrk', ['BclXL'])
Monomer('SmacA', ['Xiap'])
Monomer('SmacC')
Monomer('ParpC')
Monomer('Bik', ['BclXL', 'Bcl2', 'Mcl1'])
Monomer('Xiap', ['Apop', 'SmacA', 'C3A'])
Monomer('C9')
Monomer('CytoCM', ['BakA', 'BaxA'])
Monomer('C3ub')
Monomer('C8pro', ['C6A', 'DISC'])
Monomer('C6A', ['C8pro'])
Monomer('Bar', ['C8A'])
Monomer('Flip', ['DISC'])
Monomer('L', ['R'])
Monomer('Bad', ['BclXL', 'Bcl2'])
Monomer('R', ['L'])
Monomer('Mcl1', ['BidM', 'BakA', 'Bik', 'Noxa'])
Monomer('CytoCA', ['ApafI'])
Monomer('CytoCC')
Monomer('BakA', ['BakA_1', 'BakA_2', 'SmacM', 'CytoCM', 'BclXL', 'Mcl1', 'BakM'])
Monomer('BaxC', ['BidM'])
Monomer('BaxA', ['BaxA_1', 'BaxA_2', 'BaxM', 'SmacM', 'CytoCM', 'BclXL', 'Bcl2'])
Monomer('ApafI', ['CytoCA'])
Monomer('BidU', ['C8A'])
Monomer('BidT')
Monomer('C3A', ['ParpU', 'Xiap', 'C6pro'])
Monomer('C3pro', ['C8A', 'Apop'])
Monomer('ApafA')
Monomer('BidM', ['BaxC', 'Mcl1', 'Bcl2', 'BclXL', 'BakM', 'BaxM'])
Monomer('BakM', ['BidM', 'BakA'])
Monomer('BclXL', ['BidM', 'BakA', 'BaxA', 'Hrk', 'Bik', 'Bad'])
Monomer('Bcl2', ['BidM', 'BaxA', 'Bik', 'Bad'])
Monomer('C6pro', ['C3A'])

Parameter('BakA_formation_0_2kf', 1.0)
Parameter('BakA_formation_0_1kr', 1.0)
Parameter('BakA_formation_1_2kf', 1.0)
Parameter('BakA_formation_1_1kr', 1.0)
Parameter('BakA_formation_2_2kf', 1.0)
Parameter('BakA_formation_2_1kr', 1.0)
Parameter('BaxA_formation_0_2kf', 1.0)
Parameter('BaxA_formation_0_1kr', 1.0)
Parameter('BaxA_formation_1_2kf', 1.0)
Parameter('BaxA_formation_1_1kr', 1.0)
Parameter('BaxA_formation_2_2kf', 1.0)
Parameter('BaxA_formation_2_1kr', 1.0)
Parameter('ApafA_C9_conversion_Apop_0_2kf', 1.0)
Parameter('ApafA_C9_conversion_Apop_0_1kr', 1.0)
Parameter('Xiap_inhibition_Apop_0_2kf', 1.0)
Parameter('Xiap_inhibition_Apop_0_1kr', 1.0)
Parameter('BidM_BaxC_catalysis_BaxM_0_1kc', 1.0)
Parameter('BaxA_self_catalyze_BaxM_0_2kf', 1.0)
Parameter('BaxA_self_catalyze_BaxM_0_1kr', 1.0)
Parameter('BaxA_self_catalyze_BaxM_1_1kc', 1.0)
Parameter('BidM_substrate_binding_BaxC_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BaxC_0_1kr', 1.0)
Parameter('Bar_inhibition_C8A_0_2kf', 1.0)
Parameter('Bar_inhibition_C8A_0_1kr', 1.0)
Parameter('C6A_C8pro_catalysis_C8A_0_1kc', 1.0)
Parameter('DISC_C8pro_catalysis_C8A_0_1kc', 1.0)
Parameter('C6A_substrate_binding_C8pro_0_2kf', 1.0)
Parameter('C6A_substrate_binding_C8pro_0_1kr', 1.0)
Parameter('DISC_substrate_binding_C8pro_0_2kf', 1.0)
Parameter('DISC_substrate_binding_C8pro_0_1kr', 1.0)
Parameter('L_R_dimerization_DISC_0_1kc', 1.0)
Parameter('Flip_inhibition_DISC_0_2kf', 1.0)
Parameter('Flip_inhibition_DISC_0_1kr', 1.0)
Parameter('L_dimer_binding_R_0_2kf', 1.0)
Parameter('L_dimer_binding_R_0_1kr', 1.0)
Parameter('SmacC_equilibration_SmacA_0_1kf', 1.0)
Parameter('SmacC_equilibration_SmacA_0_1kr', 1.0)
Parameter('Xiap_inhibition_SmacA_0_2kf', 1.0)
Parameter('Xiap_inhibition_SmacA_0_1kr', 1.0)
Parameter('BakA_SmacM_transport_SmacC_0_1kc', 1.0)
Parameter('BaxA_SmacM_transport_SmacC_0_1kc', 1.0)
Parameter('BakA_transport_binding_SmacM_0_2kf', 1.0)
Parameter('BakA_transport_binding_SmacM_0_1kr', 1.0)
Parameter('BaxA_transport_binding_SmacM_0_2kf', 1.0)
Parameter('BaxA_transport_binding_SmacM_0_1kr', 1.0)
Parameter('C3A_ParpU_catalysis_ParpC_0_1kc', 1.0)
Parameter('C3A_substrate_binding_ParpU_0_2kf', 1.0)
Parameter('C3A_substrate_binding_ParpU_0_1kr', 1.0)
Parameter('Mcl1_inhibition_BidM_0_2kf', 1.0)
Parameter('Mcl1_inhibition_BidM_0_1kr', 1.0)
Parameter('Bcl2_inhibition_BidM_0_2kf', 1.0)
Parameter('Bcl2_inhibition_BidM_0_1kr', 1.0)
Parameter('BclXL_inhibition_BidM_0_2kf', 1.0)
Parameter('BclXL_inhibition_BidM_0_1kr', 1.0)
Parameter('BidT_equilibration_BidM_0_1kf', 1.0)
Parameter('BidT_equilibration_BidM_0_1kr', 1.0)
Parameter('C3A_Xiap_catalysis_C3ub_0_1kc', 1.0)
Parameter('Xiap_substrate_binding_C3A_0_2kf', 1.0)
Parameter('Xiap_substrate_binding_C3A_0_1kr', 1.0)
Parameter('C3A_C6pro_catalysis_C6A_0_1kc', 1.0)
Parameter('C3A_substrate_binding_C6pro_0_2kf', 1.0)
Parameter('C3A_substrate_binding_C6pro_0_1kr', 1.0)
Parameter('CytoCC_equilibration_CytoCA_0_1kf', 1.0)
Parameter('CytoCC_equilibration_CytoCA_0_1kr', 1.0)
Parameter('BakA_CytoCM_transport_CytoCC_0_1kc', 1.0)
Parameter('BaxA_CytoCM_transport_CytoCC_0_1kc', 1.0)
Parameter('BakA_transport_binding_CytoCM_0_2kf', 1.0)
Parameter('BakA_transport_binding_CytoCM_0_1kr', 1.0)
Parameter('BaxA_transport_binding_CytoCM_0_2kf', 1.0)
Parameter('BaxA_transport_binding_CytoCM_0_1kr', 1.0)
Parameter('BclXL_inhibition_BakA_0_2kf', 1.0)
Parameter('BclXL_inhibition_BakA_0_1kr', 1.0)
Parameter('Mcl1_inhibition_BakA_0_2kf', 1.0)
Parameter('Mcl1_inhibition_BakA_0_1kr', 1.0)
Parameter('BidM_BakM_catalysis_BakA_0_1kc', 1.0)
Parameter('BidM_substrate_binding_BakM_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BakM_0_1kr', 1.0)
Parameter('BclXL_inhibition_BaxA_0_2kf', 1.0)
Parameter('BclXL_inhibition_BaxA_0_1kr', 1.0)
Parameter('Bcl2_inhibition_BaxA_0_2kf', 1.0)
Parameter('Bcl2_inhibition_BaxA_0_1kr', 1.0)
Parameter('BaxM_BidM_catalysis_BaxA_0_1kc', 1.0)
Parameter('BidM_substrate_binding_BaxM_0_2kf', 1.0)
Parameter('BidM_substrate_binding_BaxM_0_1kr', 1.0)
Parameter('C8A_BidU_catalysis_BidT_0_1kc', 1.0)
Parameter('C8A_substrate_binding_BidU_0_2kf', 1.0)
Parameter('C8A_substrate_binding_BidU_0_1kr', 1.0)
Parameter('C8A_C3pro_catalysis_C3A_0_1kc', 1.0)
Parameter('Apop_C3pro_catalysis_C3A_0_1kc', 1.0)
Parameter('C8A_substrate_binding_C3pro_0_2kf', 1.0)
Parameter('C8A_substrate_binding_C3pro_0_1kr', 1.0)
Parameter('Apop_substrate_binding_C3pro_0_2kf', 1.0)
Parameter('Apop_substrate_binding_C3pro_0_1kr', 1.0)
Parameter('CytoCA_ApafI_catalysis_ApafA_0_1kc', 1.0)
Parameter('CytoCA_substrate_binding_ApafI_0_2kf', 1.0)
Parameter('CytoCA_substrate_binding_ApafI_0_1kr', 1.0)
Parameter('BakA_self_catalyze_BakM_0_2kf', 1.0)
Parameter('BakA_self_catalyze_BakM_0_1kr', 1.0)
Parameter('BakA_self_catalyze_BakM_1_1kc', 1.0)
Parameter('Hrk_inhibition_BclXL_0_2kf', 1.0)
Parameter('Hrk_inhibition_BclXL_0_1kr', 1.0)
Parameter('Bik_inhibition_BclXL_0_2kf', 1.0)
Parameter('Bik_inhibition_BclXL_0_1kr', 1.0)
Parameter('Bad_inhibition_BclXL_0_2kf', 1.0)
Parameter('Bad_inhibition_BclXL_0_1kr', 1.0)
Parameter('Bik_inhibition_Bcl2_0_2kf', 1.0)
Parameter('Bik_inhibition_Bcl2_0_1kr', 1.0)
Parameter('Bad_inhibition_Bcl2_0_2kf', 1.0)
Parameter('Bad_inhibition_Bcl2_0_1kr', 1.0)
Parameter('Bik_inhibition_Mcl1_0_2kf', 1.0)
Parameter('Bik_inhibition_Mcl1_0_1kr', 1.0)
Parameter('Noxa_inhibition_Mcl1_0_2kf', 1.0)
Parameter('Noxa_inhibition_Mcl1_0_1kr', 1.0)
Parameter('Noxa_0', 7000.0)
Parameter('Apop_0', 0.0)
Parameter('ParpU_0', 1000000.0)
Parameter('C8A_0', 0.0)
Parameter('DISC_0', 0.0)
Parameter('SmacM_0', 100000.0)
Parameter('BaxM_0', 0.0)
Parameter('Hrk_0', 6000.0)
Parameter('SmacA_0', 0.0)
Parameter('SmacC_0', 0.0)
Parameter('ParpC_0', 0.0)
Parameter('Bik_0', 9000.0)
Parameter('Xiap_0', 100000.0)
Parameter('C9_0', 100000.0)
Parameter('CytoCM_0', 500000.0)
Parameter('C3ub_0', 0.0)
Parameter('C8pro_0', 20000.0)
Parameter('C6A_0', 0.0)
Parameter('Bar_0', 1000.0)
Parameter('Flip_0', 100.0)
Parameter('L_0', 3000.0)
Parameter('Bad_0', 29000.0)
Parameter('R_0', 200.0)
Parameter('Mcl1_0', 47000.0)
Parameter('CytoCA_0', 0.0)
Parameter('CytoCC_0', 0.0)
Parameter('BakA_0', 0.0)
Parameter('BaxC_0', 35000.0)
Parameter('BaxA_0', 0.0)
Parameter('ApafI_0', 100000.0)
Parameter('BidU_0', 167000.0)
Parameter('BidT_0', 0.0)
Parameter('C3A_0', 0.0)
Parameter('C3pro_0', 10000.0)
Parameter('ApafA_0', 0.0)
Parameter('BidM_0', 0.0)
Parameter('BakM_0', 30000.0)
Parameter('BclXL_0', 98000.0)
Parameter('Bcl2_0', 150000.0)
Parameter('C6pro_0', 10000.0)

Observable('Noxa_0_obs', Noxa(Mcl1=None))
Observable('Noxa_1_obs', Noxa(Mcl1=ANY))
Observable('Apop_0_obs', Apop(Xiap=None, C3pro=None))
Observable('Apop_1_obs', Apop(Xiap=None, C3pro=ANY))
Observable('Apop_2_obs', Apop(Xiap=ANY, C3pro=None))
Observable('Apop_3_obs', Apop(Xiap=ANY, C3pro=ANY))
Observable('ParpU_0_obs', ParpU(C3A=None))
Observable('ParpU_1_obs', ParpU(C3A=ANY))
Observable('C8A_0_obs', C8A(Bar=None, BidU=None, C3pro=None))
Observable('C8A_1_obs', C8A(Bar=None, BidU=None, C3pro=ANY))
Observable('C8A_2_obs', C8A(Bar=None, BidU=ANY, C3pro=None))
Observable('C8A_3_obs', C8A(Bar=None, BidU=ANY, C3pro=ANY))
Observable('C8A_4_obs', C8A(Bar=ANY, BidU=None, C3pro=None))
Observable('C8A_5_obs', C8A(Bar=ANY, BidU=None, C3pro=ANY))
Observable('C8A_6_obs', C8A(Bar=ANY, BidU=ANY, C3pro=None))
Observable('C8A_7_obs', C8A(Bar=ANY, BidU=ANY, C3pro=ANY))
Observable('DISC_0_obs', DISC(C8pro=None, Flip=None))
Observable('DISC_1_obs', DISC(C8pro=None, Flip=ANY))
Observable('DISC_2_obs', DISC(C8pro=ANY, Flip=None))
Observable('DISC_3_obs', DISC(C8pro=ANY, Flip=ANY))
Observable('SmacM_0_obs', SmacM(BakA=None, BaxA=None))
Observable('SmacM_1_obs', SmacM(BakA=None, BaxA=ANY))
Observable('SmacM_2_obs', SmacM(BakA=ANY, BaxA=None))
Observable('SmacM_3_obs', SmacM(BakA=ANY, BaxA=ANY))
Observable('BaxM_0_obs', BaxM(BaxA=None, BidM=None))
Observable('BaxM_1_obs', BaxM(BaxA=None, BidM=ANY))
Observable('BaxM_2_obs', BaxM(BaxA=ANY, BidM=None))
Observable('BaxM_3_obs', BaxM(BaxA=ANY, BidM=ANY))
Observable('Hrk_0_obs', Hrk(BclXL=None))
Observable('Hrk_1_obs', Hrk(BclXL=ANY))
Observable('SmacA_0_obs', SmacA(Xiap=None))
Observable('SmacA_1_obs', SmacA(Xiap=ANY))
Observable('SmacC_0_obs', SmacC())
Observable('ParpC_0_obs', ParpC())
Observable('Bik_0_obs', Bik(BclXL=None, Bcl2=None, Mcl1=None))
Observable('Bik_1_obs', Bik(BclXL=None, Bcl2=None, Mcl1=ANY))
Observable('Bik_2_obs', Bik(BclXL=None, Bcl2=ANY, Mcl1=None))
Observable('Bik_3_obs', Bik(BclXL=None, Bcl2=ANY, Mcl1=ANY))
Observable('Bik_4_obs', Bik(BclXL=ANY, Bcl2=None, Mcl1=None))
Observable('Bik_5_obs', Bik(BclXL=ANY, Bcl2=None, Mcl1=ANY))
Observable('Bik_6_obs', Bik(BclXL=ANY, Bcl2=ANY, Mcl1=None))
Observable('Bik_7_obs', Bik(BclXL=ANY, Bcl2=ANY, Mcl1=ANY))
Observable('Xiap_0_obs', Xiap(Apop=None, SmacA=None, C3A=None))
Observable('Xiap_1_obs', Xiap(Apop=None, SmacA=None, C3A=ANY))
Observable('Xiap_2_obs', Xiap(Apop=None, SmacA=ANY, C3A=None))
Observable('Xiap_3_obs', Xiap(Apop=None, SmacA=ANY, C3A=ANY))
Observable('Xiap_4_obs', Xiap(Apop=ANY, SmacA=None, C3A=None))
Observable('Xiap_5_obs', Xiap(Apop=ANY, SmacA=None, C3A=ANY))
Observable('Xiap_6_obs', Xiap(Apop=ANY, SmacA=ANY, C3A=None))
Observable('Xiap_7_obs', Xiap(Apop=ANY, SmacA=ANY, C3A=ANY))
Observable('C9_0_obs', C9())
Observable('CytoCM_0_obs', CytoCM(BakA=None, BaxA=None))
Observable('CytoCM_1_obs', CytoCM(BakA=None, BaxA=ANY))
Observable('CytoCM_2_obs', CytoCM(BakA=ANY, BaxA=None))
Observable('CytoCM_3_obs', CytoCM(BakA=ANY, BaxA=ANY))
Observable('C3ub_0_obs', C3ub())
Observable('C8pro_0_obs', C8pro(C6A=None, DISC=None))
Observable('C8pro_1_obs', C8pro(C6A=None, DISC=ANY))
Observable('C8pro_2_obs', C8pro(C6A=ANY, DISC=None))
Observable('C8pro_3_obs', C8pro(C6A=ANY, DISC=ANY))
Observable('C6A_0_obs', C6A(C8pro=None))
Observable('C6A_1_obs', C6A(C8pro=ANY))
Observable('Bar_0_obs', Bar(C8A=None))
Observable('Bar_1_obs', Bar(C8A=ANY))
Observable('Flip_0_obs', Flip(DISC=None))
Observable('Flip_1_obs', Flip(DISC=ANY))
Observable('L_0_obs', L(R=None))
Observable('L_1_obs', L(R=ANY))
Observable('Bad_0_obs', Bad(BclXL=None, Bcl2=None))
Observable('Bad_1_obs', Bad(BclXL=None, Bcl2=ANY))
Observable('Bad_2_obs', Bad(BclXL=ANY, Bcl2=None))
Observable('Bad_3_obs', Bad(BclXL=ANY, Bcl2=ANY))
Observable('R_0_obs', R(L=None))
Observable('R_1_obs', R(L=ANY))
Observable('Mcl1_0_obs', Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None))
Observable('Mcl1_1_obs', Mcl1(BidM=None, BakA=None, Bik=None, Noxa=ANY))
Observable('Mcl1_2_obs', Mcl1(BidM=None, BakA=None, Bik=ANY, Noxa=None))
Observable('Mcl1_3_obs', Mcl1(BidM=None, BakA=None, Bik=ANY, Noxa=ANY))
Observable('Mcl1_4_obs', Mcl1(BidM=None, BakA=ANY, Bik=None, Noxa=None))
Observable('Mcl1_5_obs', Mcl1(BidM=None, BakA=ANY, Bik=None, Noxa=ANY))
Observable('Mcl1_6_obs', Mcl1(BidM=None, BakA=ANY, Bik=ANY, Noxa=None))
Observable('Mcl1_7_obs', Mcl1(BidM=None, BakA=ANY, Bik=ANY, Noxa=ANY))
Observable('Mcl1_8_obs', Mcl1(BidM=ANY, BakA=None, Bik=None, Noxa=None))
Observable('Mcl1_9_obs', Mcl1(BidM=ANY, BakA=None, Bik=None, Noxa=ANY))
Observable('Mcl1_10_obs', Mcl1(BidM=ANY, BakA=None, Bik=ANY, Noxa=None))
Observable('Mcl1_11_obs', Mcl1(BidM=ANY, BakA=None, Bik=ANY, Noxa=ANY))
Observable('Mcl1_12_obs', Mcl1(BidM=ANY, BakA=ANY, Bik=None, Noxa=None))
Observable('Mcl1_13_obs', Mcl1(BidM=ANY, BakA=ANY, Bik=None, Noxa=ANY))
Observable('Mcl1_14_obs', Mcl1(BidM=ANY, BakA=ANY, Bik=ANY, Noxa=None))
Observable('Mcl1_15_obs', Mcl1(BidM=ANY, BakA=ANY, Bik=ANY, Noxa=ANY))
Observable('CytoCA_0_obs', CytoCA(ApafI=None))
Observable('CytoCA_1_obs', CytoCA(ApafI=ANY))
Observable('CytoCC_0_obs', CytoCC())
Observable('BakA_0_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_1_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_2_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_3_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_4_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_5_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_6_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_7_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_8_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_9_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_10_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_11_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_12_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_13_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_14_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_15_obs', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_16_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_17_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_18_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_19_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_20_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_21_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_22_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_23_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_24_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_25_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_26_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_27_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_28_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_29_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_30_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_31_obs', BakA(BakA_1=None, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_32_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_33_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_34_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_35_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_36_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_37_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_38_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_39_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_40_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_41_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_42_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_43_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_44_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_45_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_46_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_47_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_48_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_49_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_50_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_51_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_52_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_53_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_54_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_55_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_56_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_57_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_58_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_59_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_60_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_61_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_62_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_63_obs', BakA(BakA_1=None, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_64_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_65_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_66_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_67_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_68_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_69_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_70_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_71_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_72_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_73_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_74_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_75_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_76_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_77_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_78_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_79_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_80_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_81_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_82_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_83_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_84_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_85_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_86_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_87_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_88_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_89_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_90_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_91_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_92_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_93_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_94_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_95_obs', BakA(BakA_1=ANY, BakA_2=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_96_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_97_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_98_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_99_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_100_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_101_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_102_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_103_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_104_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_105_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_106_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_107_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_108_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_109_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_110_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_111_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_112_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_113_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_114_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_115_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_116_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_117_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_118_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_119_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BakA_120_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=None))
Observable('BakA_121_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=None, BakM=ANY))
Observable('BakA_122_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=None))
Observable('BakA_123_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Mcl1=ANY, BakM=ANY))
Observable('BakA_124_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=None))
Observable('BakA_125_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=None, BakM=ANY))
Observable('BakA_126_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=None))
Observable('BakA_127_obs', BakA(BakA_1=ANY, BakA_2=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Mcl1=ANY, BakM=ANY))
Observable('BaxC_0_obs', BaxC(BidM=None))
Observable('BaxC_1_obs', BaxC(BidM=ANY))
Observable('BaxA_0_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_1_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_2_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_3_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_4_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_5_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_6_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_7_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_8_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_9_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_10_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_11_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_12_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_13_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_14_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_15_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_16_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_17_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_18_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_19_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_20_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_21_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_22_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_23_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_24_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_25_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_26_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_27_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_28_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_29_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_30_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_31_obs', BaxA(BaxA_1=None, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_32_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_33_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_34_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_35_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_36_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_37_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_38_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_39_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_40_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_41_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_42_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_43_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_44_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_45_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_46_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_47_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_48_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_49_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_50_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_51_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_52_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_53_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_54_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_55_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_56_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_57_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_58_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_59_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_60_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_61_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_62_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_63_obs', BaxA(BaxA_1=None, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_64_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_65_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_66_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_67_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_68_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_69_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_70_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_71_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_72_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_73_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_74_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_75_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_76_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_77_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_78_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_79_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_80_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_81_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_82_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_83_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_84_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_85_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_86_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_87_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_88_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_89_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_90_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_91_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_92_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_93_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_94_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_95_obs', BaxA(BaxA_1=ANY, BaxA_2=None, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_96_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_97_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_98_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_99_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_100_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_101_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_102_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_103_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_104_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_105_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_106_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_107_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_108_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_109_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_110_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_111_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=None, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_112_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_113_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_114_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_115_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_116_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_117_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_118_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_119_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=None, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_120_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=None))
Observable('BaxA_121_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=None, Bcl2=ANY))
Observable('BaxA_122_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=None))
Observable('BaxA_123_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=None, BclXL=ANY, Bcl2=ANY))
Observable('BaxA_124_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=None))
Observable('BaxA_125_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=None, Bcl2=ANY))
Observable('BaxA_126_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=None))
Observable('BaxA_127_obs', BaxA(BaxA_1=ANY, BaxA_2=ANY, BaxM=ANY, SmacM=ANY, CytoCM=ANY, BclXL=ANY, Bcl2=ANY))
Observable('ApafI_0_obs', ApafI(CytoCA=None))
Observable('ApafI_1_obs', ApafI(CytoCA=ANY))
Observable('BidU_0_obs', BidU(C8A=None))
Observable('BidU_1_obs', BidU(C8A=ANY))
Observable('BidT_0_obs', BidT())
Observable('C3A_0_obs', C3A(ParpU=None, Xiap=None, C6pro=None))
Observable('C3A_1_obs', C3A(ParpU=None, Xiap=None, C6pro=ANY))
Observable('C3A_2_obs', C3A(ParpU=None, Xiap=ANY, C6pro=None))
Observable('C3A_3_obs', C3A(ParpU=None, Xiap=ANY, C6pro=ANY))
Observable('C3A_4_obs', C3A(ParpU=ANY, Xiap=None, C6pro=None))
Observable('C3A_5_obs', C3A(ParpU=ANY, Xiap=None, C6pro=ANY))
Observable('C3A_6_obs', C3A(ParpU=ANY, Xiap=ANY, C6pro=None))
Observable('C3A_7_obs', C3A(ParpU=ANY, Xiap=ANY, C6pro=ANY))
Observable('C3pro_0_obs', C3pro(C8A=None, Apop=None))
Observable('C3pro_1_obs', C3pro(C8A=None, Apop=ANY))
Observable('C3pro_2_obs', C3pro(C8A=ANY, Apop=None))
Observable('C3pro_3_obs', C3pro(C8A=ANY, Apop=ANY))
Observable('ApafA_0_obs', ApafA())
Observable('BidM_0_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_1_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_2_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_3_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_4_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_5_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_6_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_7_obs', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_8_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_9_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_10_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_11_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_12_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_13_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_14_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_15_obs', BidM(BaxC=None, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_16_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_17_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_18_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_19_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_20_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_21_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_22_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_23_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_24_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_25_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_26_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_27_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_28_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_29_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_30_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_31_obs', BidM(BaxC=None, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_32_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_33_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_34_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_35_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_36_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_37_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_38_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_39_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_40_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_41_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_42_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_43_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_44_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_45_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_46_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_47_obs', BidM(BaxC=ANY, Mcl1=None, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_48_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_49_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_50_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_51_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_52_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_53_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_54_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_55_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=None, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BidM_56_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=None, BaxM=None))
Observable('BidM_57_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=None, BaxM=ANY))
Observable('BidM_58_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=None))
Observable('BidM_59_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=None, BakM=ANY, BaxM=ANY))
Observable('BidM_60_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=None))
Observable('BidM_61_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=None, BaxM=ANY))
Observable('BidM_62_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=None))
Observable('BidM_63_obs', BidM(BaxC=ANY, Mcl1=ANY, Bcl2=ANY, BclXL=ANY, BakM=ANY, BaxM=ANY))
Observable('BakM_0_obs', BakM(BidM=None, BakA=None))
Observable('BakM_1_obs', BakM(BidM=None, BakA=ANY))
Observable('BakM_2_obs', BakM(BidM=ANY, BakA=None))
Observable('BakM_3_obs', BakM(BidM=ANY, BakA=ANY))
Observable('BclXL_0_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_1_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_2_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_3_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_4_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_5_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_6_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_7_obs', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_8_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_9_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_10_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_11_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_12_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_13_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_14_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_15_obs', BclXL(BidM=None, BakA=None, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_16_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_17_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_18_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_19_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_20_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_21_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_22_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_23_obs', BclXL(BidM=None, BakA=ANY, BaxA=None, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_24_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_25_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_26_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_27_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_28_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_29_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_30_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_31_obs', BclXL(BidM=None, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_32_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_33_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_34_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_35_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_36_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_37_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_38_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_39_obs', BclXL(BidM=ANY, BakA=None, BaxA=None, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_40_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_41_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_42_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_43_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_44_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_45_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_46_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_47_obs', BclXL(BidM=ANY, BakA=None, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_48_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_49_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_50_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_51_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_52_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_53_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_54_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_55_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=None, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('BclXL_56_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=None, Bik=None, Bad=None))
Observable('BclXL_57_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=None, Bik=None, Bad=ANY))
Observable('BclXL_58_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=None, Bik=ANY, Bad=None))
Observable('BclXL_59_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=None, Bik=ANY, Bad=ANY))
Observable('BclXL_60_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=None, Bad=None))
Observable('BclXL_61_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=None, Bad=ANY))
Observable('BclXL_62_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=None))
Observable('BclXL_63_obs', BclXL(BidM=ANY, BakA=ANY, BaxA=ANY, Hrk=ANY, Bik=ANY, Bad=ANY))
Observable('Bcl2_0_obs', Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None))
Observable('Bcl2_1_obs', Bcl2(BidM=None, BaxA=None, Bik=None, Bad=ANY))
Observable('Bcl2_2_obs', Bcl2(BidM=None, BaxA=None, Bik=ANY, Bad=None))
Observable('Bcl2_3_obs', Bcl2(BidM=None, BaxA=None, Bik=ANY, Bad=ANY))
Observable('Bcl2_4_obs', Bcl2(BidM=None, BaxA=ANY, Bik=None, Bad=None))
Observable('Bcl2_5_obs', Bcl2(BidM=None, BaxA=ANY, Bik=None, Bad=ANY))
Observable('Bcl2_6_obs', Bcl2(BidM=None, BaxA=ANY, Bik=ANY, Bad=None))
Observable('Bcl2_7_obs', Bcl2(BidM=None, BaxA=ANY, Bik=ANY, Bad=ANY))
Observable('Bcl2_8_obs', Bcl2(BidM=ANY, BaxA=None, Bik=None, Bad=None))
Observable('Bcl2_9_obs', Bcl2(BidM=ANY, BaxA=None, Bik=None, Bad=ANY))
Observable('Bcl2_10_obs', Bcl2(BidM=ANY, BaxA=None, Bik=ANY, Bad=None))
Observable('Bcl2_11_obs', Bcl2(BidM=ANY, BaxA=None, Bik=ANY, Bad=ANY))
Observable('Bcl2_12_obs', Bcl2(BidM=ANY, BaxA=ANY, Bik=None, Bad=None))
Observable('Bcl2_13_obs', Bcl2(BidM=ANY, BaxA=ANY, Bik=None, Bad=ANY))
Observable('Bcl2_14_obs', Bcl2(BidM=ANY, BaxA=ANY, Bik=ANY, Bad=None))
Observable('Bcl2_15_obs', Bcl2(BidM=ANY, BaxA=ANY, Bik=ANY, Bad=ANY))
Observable('C6pro_0_obs', C6pro(C3A=None))
Observable('C6pro_1_obs', C6pro(C3A=ANY))
Observable('Noxa_obs', Noxa())
Observable('Apop_obs', Apop())
Observable('ParpU_obs', ParpU())
Observable('C8A_obs', C8A())
Observable('DISC_obs', DISC())
Observable('SmacM_obs', SmacM())
Observable('BaxM_obs', BaxM())
Observable('Hrk_obs', Hrk())
Observable('SmacA_obs', SmacA())
Observable('SmacC_obs', SmacC())
Observable('ParpC_obs', ParpC())
Observable('Bik_obs', Bik())
Observable('Xiap_obs', Xiap())
Observable('C9_obs', C9())
Observable('CytoCM_obs', CytoCM())
Observable('C3ub_obs', C3ub())
Observable('C8pro_obs', C8pro())
Observable('C6A_obs', C6A())
Observable('Bar_obs', Bar())
Observable('Flip_obs', Flip())
Observable('L_obs', L())
Observable('Bad_obs', Bad())
Observable('R_obs', R())
Observable('Mcl1_obs', Mcl1())
Observable('CytoCA_obs', CytoCA())
Observable('CytoCC_obs', CytoCC())
Observable('BakA_obs', BakA())
Observable('BaxC_obs', BaxC())
Observable('BaxA_obs', BaxA())
Observable('ApafI_obs', ApafI())
Observable('BidU_obs', BidU())
Observable('BidT_obs', BidT())
Observable('C3A_obs', C3A())
Observable('C3pro_obs', C3pro())
Observable('ApafA_obs', ApafA())
Observable('BidM_obs', BidM())
Observable('BakM_obs', BakM())
Observable('BclXL_obs', BclXL())
Observable('Bcl2_obs', Bcl2())
Observable('C6pro_obs', C6pro())

Rule('BakA_formation_0', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) <> BakA(BakA_1=None, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BakA_formation_0_2kf, BakA_formation_0_1kr)
Rule('BakA_formation_1', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + BakA(BakA_1=None, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) <> BakA(BakA_1=3, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BakA_formation_1_2kf, BakA_formation_1_1kr)
Rule('BakA_formation_2', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + BakA(BakA_1=3, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) <> BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BakA_formation_2_2kf, BakA_formation_2_1kr)
Rule('BaxA_formation_0', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) <> BaxA(BaxA_1=None, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxA_formation_0_2kf, BaxA_formation_0_1kr)
Rule('BaxA_formation_1', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + BaxA(BaxA_1=None, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) <> BaxA(BaxA_1=3, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxA_formation_1_2kf, BaxA_formation_1_1kr)
Rule('BaxA_formation_2', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + BaxA(BaxA_1=3, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) <> BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxA_formation_2_2kf, BaxA_formation_2_1kr)
Rule('ApafA_C9_conversion_Apop_0', ApafA() + C9() <> Apop(Xiap=None, C3pro=None), ApafA_C9_conversion_Apop_0_2kf, ApafA_C9_conversion_Apop_0_1kr)
Rule('Xiap_inhibition_Apop_0', Xiap(Apop=None, SmacA=None, C3A=None) + Apop(Xiap=None, C3pro=None) <> Xiap(Apop=1, SmacA=None, C3A=None) % Apop(Xiap=1, C3pro=None), Xiap_inhibition_Apop_0_2kf, Xiap_inhibition_Apop_0_1kr)
Rule('BidM_BaxC_catalysis_BaxM_0', BidM(BaxC=1, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) % BaxC(BidM=1) >> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BaxM(BaxA=None, BidM=None), BidM_BaxC_catalysis_BaxM_0_1kc)
Rule('BaxA_self_catalyze_BaxM_0', BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + BaxM(BaxA=None, BidM=None) <> BaxA(BaxA_1=None, BaxA_2=None, BaxM=1, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxM(BaxA=1, BidM=None), BaxA_self_catalyze_BaxM_0_2kf, BaxA_self_catalyze_BaxM_0_1kr)
Rule('BaxA_self_catalyze_BaxM_1', BaxA(BaxA_1=None, BaxA_2=None, BaxM=1, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxM(BaxA=1, BidM=None) >> BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxA_self_catalyze_BaxM_1_1kc)
Rule('BidM_substrate_binding_BaxC_0', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BaxC(BidM=None) <> BidM(BaxC=1, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) % BaxC(BidM=1), BidM_substrate_binding_BaxC_0_2kf, BidM_substrate_binding_BaxC_0_1kr)
Rule('Bar_inhibition_C8A_0', Bar(C8A=None) + C8A(Bar=None, BidU=None, C3pro=None) <> Bar(C8A=1) % C8A(Bar=1, BidU=None, C3pro=None), Bar_inhibition_C8A_0_2kf, Bar_inhibition_C8A_0_1kr)
Rule('C6A_C8pro_catalysis_C8A_0', C6A(C8pro=1) % C8pro(C6A=1, DISC=None) >> C6A(C8pro=None) + C8A(Bar=None, BidU=None, C3pro=None), C6A_C8pro_catalysis_C8A_0_1kc)
Rule('DISC_C8pro_catalysis_C8A_0', DISC(C8pro=1, Flip=None) % C8pro(C6A=None, DISC=1) >> DISC(C8pro=None, Flip=None) + C8A(Bar=None, BidU=None, C3pro=None), DISC_C8pro_catalysis_C8A_0_1kc)
Rule('C6A_substrate_binding_C8pro_0', C6A(C8pro=None) + C8pro(C6A=None, DISC=None) <> C6A(C8pro=1) % C8pro(C6A=1, DISC=None), C6A_substrate_binding_C8pro_0_2kf, C6A_substrate_binding_C8pro_0_1kr)
Rule('DISC_substrate_binding_C8pro_0', DISC(C8pro=None, Flip=None) + C8pro(C6A=None, DISC=None) <> DISC(C8pro=1, Flip=None) % C8pro(C6A=None, DISC=1), DISC_substrate_binding_C8pro_0_2kf, DISC_substrate_binding_C8pro_0_1kr)
Rule('L_R_dimerization_DISC_0', L(R=1) % R(L=1) >> DISC(C8pro=None, Flip=None), L_R_dimerization_DISC_0_1kc)
Rule('Flip_inhibition_DISC_0', Flip(DISC=None) + DISC(C8pro=None, Flip=None) <> Flip(DISC=1) % DISC(C8pro=None, Flip=1), Flip_inhibition_DISC_0_2kf, Flip_inhibition_DISC_0_1kr)
Rule('L_dimer_binding_R_0', L(R=None) + R(L=None) <> L(R=1) % R(L=1), L_dimer_binding_R_0_2kf, L_dimer_binding_R_0_1kr)
Rule('SmacC_equilibration_SmacA_0', SmacC() <> SmacA(Xiap=None), SmacC_equilibration_SmacA_0_1kf, SmacC_equilibration_SmacA_0_1kr)
Rule('Xiap_inhibition_SmacA_0', Xiap(Apop=None, SmacA=None, C3A=None) + SmacA(Xiap=None) <> Xiap(Apop=None, SmacA=1, C3A=None) % SmacA(Xiap=1), Xiap_inhibition_SmacA_0_2kf, Xiap_inhibition_SmacA_0_1kr)
Rule('BakA_SmacM_transport_SmacC_0', BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=5, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % SmacM(BakA=5, BaxA=None) >> BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + SmacC(), BakA_SmacM_transport_SmacC_0_1kc)
Rule('BaxA_SmacM_transport_SmacC_0', BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=5, CytoCM=None, BclXL=None, Bcl2=None) % SmacM(BakA=None, BaxA=5) >> BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + SmacC(), BaxA_SmacM_transport_SmacC_0_1kc)
Rule('BakA_transport_binding_SmacM_0', BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + SmacM(BakA=None, BaxA=None) <> BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=5, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % SmacM(BakA=5, BaxA=None), BakA_transport_binding_SmacM_0_2kf, BakA_transport_binding_SmacM_0_1kr)
Rule('BaxA_transport_binding_SmacM_0', BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + SmacM(BakA=None, BaxA=None) <> BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=5, CytoCM=None, BclXL=None, Bcl2=None) % SmacM(BakA=None, BaxA=5), BaxA_transport_binding_SmacM_0_2kf, BaxA_transport_binding_SmacM_0_1kr)
Rule('C3A_ParpU_catalysis_ParpC_0', C3A(ParpU=1, Xiap=None, C6pro=None) % ParpU(C3A=1) >> C3A(ParpU=None, Xiap=None, C6pro=None) + ParpC(), C3A_ParpU_catalysis_ParpC_0_1kc)
Rule('C3A_substrate_binding_ParpU_0', C3A(ParpU=None, Xiap=None, C6pro=None) + ParpU(C3A=None) <> C3A(ParpU=1, Xiap=None, C6pro=None) % ParpU(C3A=1), C3A_substrate_binding_ParpU_0_2kf, C3A_substrate_binding_ParpU_0_1kr)
Rule('Mcl1_inhibition_BidM_0', Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None) + BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) <> Mcl1(BidM=1, BakA=None, Bik=None, Noxa=None) % BidM(BaxC=None, Mcl1=1, Bcl2=None, BclXL=None, BakM=None, BaxM=None), Mcl1_inhibition_BidM_0_2kf, Mcl1_inhibition_BidM_0_1kr)
Rule('Bcl2_inhibition_BidM_0', Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None) + BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) <> Bcl2(BidM=1, BaxA=None, Bik=None, Bad=None) % BidM(BaxC=None, Mcl1=None, Bcl2=1, BclXL=None, BakM=None, BaxM=None), Bcl2_inhibition_BidM_0_2kf, Bcl2_inhibition_BidM_0_1kr)
Rule('BclXL_inhibition_BidM_0', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) + BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) <> BclXL(BidM=1, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) % BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=1, BakM=None, BaxM=None), BclXL_inhibition_BidM_0_2kf, BclXL_inhibition_BidM_0_1kr)
Rule('BidT_equilibration_BidM_0', BidT() <> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None), BidT_equilibration_BidM_0_1kf, BidT_equilibration_BidM_0_1kr)
Rule('C3A_Xiap_catalysis_C3ub_0', Xiap(Apop=None, SmacA=None, C3A=1) % C3A(ParpU=None, Xiap=1, C6pro=None) >> Xiap(Apop=None, SmacA=None, C3A=None) + C3ub(), C3A_Xiap_catalysis_C3ub_0_1kc)
Rule('Xiap_substrate_binding_C3A_0', Xiap(Apop=None, SmacA=None, C3A=None) + C3A(ParpU=None, Xiap=None, C6pro=None) <> Xiap(Apop=None, SmacA=None, C3A=1) % C3A(ParpU=None, Xiap=1, C6pro=None), Xiap_substrate_binding_C3A_0_2kf, Xiap_substrate_binding_C3A_0_1kr)
Rule('C3A_C6pro_catalysis_C6A_0', C3A(ParpU=None, Xiap=None, C6pro=1) % C6pro(C3A=1) >> C3A(ParpU=None, Xiap=None, C6pro=None) + C6A(C8pro=None), C3A_C6pro_catalysis_C6A_0_1kc)
Rule('C3A_substrate_binding_C6pro_0', C3A(ParpU=None, Xiap=None, C6pro=None) + C6pro(C3A=None) <> C3A(ParpU=None, Xiap=None, C6pro=1) % C6pro(C3A=1), C3A_substrate_binding_C6pro_0_2kf, C3A_substrate_binding_C6pro_0_1kr)
Rule('CytoCC_equilibration_CytoCA_0', CytoCC() <> CytoCA(ApafI=None), CytoCC_equilibration_CytoCA_0_1kf, CytoCC_equilibration_CytoCA_0_1kr)
Rule('BakA_CytoCM_transport_CytoCC_0', BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=5, BclXL=None, Mcl1=None, BakM=None) % CytoCM(BakA=5, BaxA=None) >> BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + CytoCC(), BakA_CytoCM_transport_CytoCC_0_1kc)
Rule('BaxA_CytoCM_transport_CytoCC_0', BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=5, BclXL=None, Bcl2=None) % CytoCM(BakA=None, BaxA=5) >> BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + CytoCC(), BaxA_CytoCM_transport_CytoCC_0_1kc)
Rule('BakA_transport_binding_CytoCM_0', BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + CytoCM(BakA=None, BaxA=None) <> BakA(BakA_1=4, BakA_2=1, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=1, BakA_2=2, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=2, BakA_2=3, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) % BakA(BakA_1=3, BakA_2=4, SmacM=None, CytoCM=5, BclXL=None, Mcl1=None, BakM=None) % CytoCM(BakA=5, BaxA=None), BakA_transport_binding_CytoCM_0_2kf, BakA_transport_binding_CytoCM_0_1kr)
Rule('BaxA_transport_binding_CytoCM_0', BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) + CytoCM(BakA=None, BaxA=None) <> BaxA(BaxA_1=4, BaxA_2=1, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=1, BaxA_2=2, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=2, BaxA_2=3, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) % BaxA(BaxA_1=3, BaxA_2=4, BaxM=None, SmacM=None, CytoCM=5, BclXL=None, Bcl2=None) % CytoCM(BakA=None, BaxA=5), BaxA_transport_binding_CytoCM_0_2kf, BaxA_transport_binding_CytoCM_0_1kr)
Rule('BclXL_inhibition_BakA_0', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) + BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) <> BclXL(BidM=None, BakA=1, BaxA=None, Hrk=None, Bik=None, Bad=None) % BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=1, Mcl1=None, BakM=None), BclXL_inhibition_BakA_0_2kf, BclXL_inhibition_BakA_0_1kr)
Rule('Mcl1_inhibition_BakA_0', Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None) + BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) <> Mcl1(BidM=None, BakA=1, Bik=None, Noxa=None) % BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=1, BakM=None), Mcl1_inhibition_BakA_0_2kf, Mcl1_inhibition_BakA_0_1kr)
Rule('BidM_BakM_catalysis_BakA_0', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=1, BaxM=None) % BakM(BidM=1, BakA=None) >> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BidM_BakM_catalysis_BakA_0_1kc)
Rule('BidM_substrate_binding_BakM_0', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BakM(BidM=None, BakA=None) <> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=1, BaxM=None) % BakM(BidM=1, BakA=None), BidM_substrate_binding_BakM_0_2kf, BidM_substrate_binding_BakM_0_1kr)
Rule('BclXL_inhibition_BaxA_0', BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) + BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) <> BclXL(BidM=None, BakA=None, BaxA=1, Hrk=None, Bik=None, Bad=None) % BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=1, Bcl2=None), BclXL_inhibition_BaxA_0_2kf, BclXL_inhibition_BaxA_0_1kr)
Rule('Bcl2_inhibition_BaxA_0', Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None) + BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None) <> Bcl2(BidM=None, BaxA=1, Bik=None, Bad=None) % BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=1), Bcl2_inhibition_BaxA_0_2kf, Bcl2_inhibition_BaxA_0_1kr)
Rule('BaxM_BidM_catalysis_BaxA_0', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=1) % BaxM(BaxA=None, BidM=1) >> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxM_BidM_catalysis_BaxA_0_1kc)
Rule('BidM_substrate_binding_BaxM_0', BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None) + BaxM(BaxA=None, BidM=None) <> BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=1) % BaxM(BaxA=None, BidM=1), BidM_substrate_binding_BaxM_0_2kf, BidM_substrate_binding_BaxM_0_1kr)
Rule('C8A_BidU_catalysis_BidT_0', C8A(Bar=None, BidU=1, C3pro=None) % BidU(C8A=1) >> C8A(Bar=None, BidU=None, C3pro=None) + BidT(), C8A_BidU_catalysis_BidT_0_1kc)
Rule('C8A_substrate_binding_BidU_0', C8A(Bar=None, BidU=None, C3pro=None) + BidU(C8A=None) <> C8A(Bar=None, BidU=1, C3pro=None) % BidU(C8A=1), C8A_substrate_binding_BidU_0_2kf, C8A_substrate_binding_BidU_0_1kr)
Rule('C8A_C3pro_catalysis_C3A_0', C8A(Bar=None, BidU=None, C3pro=1) % C3pro(C8A=1, Apop=None) >> C8A(Bar=None, BidU=None, C3pro=None) + C3A(ParpU=None, Xiap=None, C6pro=None), C8A_C3pro_catalysis_C3A_0_1kc)
Rule('Apop_C3pro_catalysis_C3A_0', Apop(Xiap=None, C3pro=1) % C3pro(C8A=None, Apop=1) >> Apop(Xiap=None, C3pro=None) + C3A(ParpU=None, Xiap=None, C6pro=None), Apop_C3pro_catalysis_C3A_0_1kc)
Rule('C8A_substrate_binding_C3pro_0', C8A(Bar=None, BidU=None, C3pro=None) + C3pro(C8A=None, Apop=None) <> C8A(Bar=None, BidU=None, C3pro=1) % C3pro(C8A=1, Apop=None), C8A_substrate_binding_C3pro_0_2kf, C8A_substrate_binding_C3pro_0_1kr)
Rule('Apop_substrate_binding_C3pro_0', Apop(Xiap=None, C3pro=None) + C3pro(C8A=None, Apop=None) <> Apop(Xiap=None, C3pro=1) % C3pro(C8A=None, Apop=1), Apop_substrate_binding_C3pro_0_2kf, Apop_substrate_binding_C3pro_0_1kr)
Rule('CytoCA_ApafI_catalysis_ApafA_0', CytoCA(ApafI=1) % ApafI(CytoCA=1) >> CytoCA(ApafI=None) + ApafA(), CytoCA_ApafI_catalysis_ApafA_0_1kc)
Rule('CytoCA_substrate_binding_ApafI_0', CytoCA(ApafI=None) + ApafI(CytoCA=None) <> CytoCA(ApafI=1) % ApafI(CytoCA=1), CytoCA_substrate_binding_ApafI_0_2kf, CytoCA_substrate_binding_ApafI_0_1kr)
Rule('BakA_self_catalyze_BakM_0', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + BakM(BidM=None, BakA=None) <> BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=1) % BakM(BidM=None, BakA=1), BakA_self_catalyze_BakM_0_2kf, BakA_self_catalyze_BakM_0_1kr)
Rule('BakA_self_catalyze_BakM_1', BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=1) % BakM(BidM=None, BakA=1) >> BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None) + BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BakA_self_catalyze_BakM_1_1kc)
Rule('Hrk_inhibition_BclXL_0', Hrk(BclXL=None) + BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) <> Hrk(BclXL=1) % BclXL(BidM=None, BakA=None, BaxA=None, Hrk=1, Bik=None, Bad=None), Hrk_inhibition_BclXL_0_2kf, Hrk_inhibition_BclXL_0_1kr)
Rule('Bik_inhibition_BclXL_0', Bik(BclXL=None, Bcl2=None, Mcl1=None) + BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) <> Bik(BclXL=1, Bcl2=None, Mcl1=None) % BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=1, Bad=None), Bik_inhibition_BclXL_0_2kf, Bik_inhibition_BclXL_0_1kr)
Rule('Bad_inhibition_BclXL_0', Bad(BclXL=None, Bcl2=None) + BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None) <> Bad(BclXL=1, Bcl2=None) % BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=1), Bad_inhibition_BclXL_0_2kf, Bad_inhibition_BclXL_0_1kr)
Rule('Bik_inhibition_Bcl2_0', Bik(BclXL=None, Bcl2=None, Mcl1=None) + Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None) <> Bik(BclXL=None, Bcl2=1, Mcl1=None) % Bcl2(BidM=None, BaxA=None, Bik=1, Bad=None), Bik_inhibition_Bcl2_0_2kf, Bik_inhibition_Bcl2_0_1kr)
Rule('Bad_inhibition_Bcl2_0', Bad(BclXL=None, Bcl2=None) + Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None) <> Bad(BclXL=None, Bcl2=1) % Bcl2(BidM=None, BaxA=None, Bik=None, Bad=1), Bad_inhibition_Bcl2_0_2kf, Bad_inhibition_Bcl2_0_1kr)
Rule('Bik_inhibition_Mcl1_0', Bik(BclXL=None, Bcl2=None, Mcl1=None) + Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None) <> Bik(BclXL=None, Bcl2=None, Mcl1=1) % Mcl1(BidM=None, BakA=None, Bik=1, Noxa=None), Bik_inhibition_Mcl1_0_2kf, Bik_inhibition_Mcl1_0_1kr)
Rule('Noxa_inhibition_Mcl1_0', Noxa(Mcl1=None) + Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None) <> Noxa(Mcl1=1) % Mcl1(BidM=None, BakA=None, Bik=None, Noxa=1), Noxa_inhibition_Mcl1_0_2kf, Noxa_inhibition_Mcl1_0_1kr)

Initial(Noxa(Mcl1=None), Noxa_0)
Initial(Apop(Xiap=None, C3pro=None), Apop_0)
Initial(ParpU(C3A=None), ParpU_0)
Initial(C8A(Bar=None, BidU=None, C3pro=None), C8A_0)
Initial(DISC(C8pro=None, Flip=None), DISC_0)
Initial(SmacM(BakA=None, BaxA=None), SmacM_0)
Initial(BaxM(BaxA=None, BidM=None), BaxM_0)
Initial(Hrk(BclXL=None), Hrk_0)
Initial(SmacA(Xiap=None), SmacA_0)
Initial(SmacC(), SmacC_0)
Initial(ParpC(), ParpC_0)
Initial(Bik(BclXL=None, Bcl2=None, Mcl1=None), Bik_0)
Initial(Xiap(Apop=None, SmacA=None, C3A=None), Xiap_0)
Initial(C9(), C9_0)
Initial(CytoCM(BakA=None, BaxA=None), CytoCM_0)
Initial(C3ub(), C3ub_0)
Initial(C8pro(C6A=None, DISC=None), C8pro_0)
Initial(C6A(C8pro=None), C6A_0)
Initial(Bar(C8A=None), Bar_0)
Initial(Flip(DISC=None), Flip_0)
Initial(L(R=None), L_0)
Initial(Bad(BclXL=None, Bcl2=None), Bad_0)
Initial(R(L=None), R_0)
Initial(Mcl1(BidM=None, BakA=None, Bik=None, Noxa=None), Mcl1_0)
Initial(CytoCA(ApafI=None), CytoCA_0)
Initial(CytoCC(), CytoCC_0)
Initial(BakA(BakA_1=None, BakA_2=None, SmacM=None, CytoCM=None, BclXL=None, Mcl1=None, BakM=None), BakA_0)
Initial(BaxC(BidM=None), BaxC_0)
Initial(BaxA(BaxA_1=None, BaxA_2=None, BaxM=None, SmacM=None, CytoCM=None, BclXL=None, Bcl2=None), BaxA_0)
Initial(ApafI(CytoCA=None), ApafI_0)
Initial(BidU(C8A=None), BidU_0)
Initial(BidT(), BidT_0)
Initial(C3A(ParpU=None, Xiap=None, C6pro=None), C3A_0)
Initial(C3pro(C8A=None, Apop=None), C3pro_0)
Initial(ApafA(), ApafA_0)
Initial(BidM(BaxC=None, Mcl1=None, Bcl2=None, BclXL=None, BakM=None, BaxM=None), BidM_0)
Initial(BakM(BidM=None, BakA=None), BakM_0)
Initial(BclXL(BidM=None, BakA=None, BaxA=None, Hrk=None, Bik=None, Bad=None), BclXL_0)
Initial(Bcl2(BidM=None, BaxA=None, Bik=None, Bad=None), Bcl2_0)
Initial(C6pro(C3A=None), C6pro_0)

